version: "3"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 1001:1001
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - first-service
      - second-service

  first-service:
    build: ./firstService
    restart: unless-stopped

  second-service:
    build: ./secondService
    restart: unless-stopped

volumes:
  first-service:
  second-service:
